export default {
    'type_id': 7,
    'number': '',
    'contractor_id': null,
    'subjects': '',
    'date_start': '',
    'date_finish': '',
    'prolongation_id': '',
    'prolongation_term': '',
    'responsible_id': '',
    'creator_id': '',
    'permanent': false,

    'contracts': [],
    'applications': [],
    'specifications': [],
    'delivery_acts': [],
    'others': [],
    'annul_doc': [],

    'contracts_list': [],
    'applications_list': [],
    'specifications_list': [],
    'delivery_acts_list': [],
    'others_list': [],
    'annul_doc_list': [],

    'archive': '',
    'wagons': [],
    'additional_licenses': [],
}
